Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.1.98"
  config.vm.hostname = "file.browser"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y python-dev --upgrade
      sudo apt-get install -y python-pip --upgrade
      sudo pip install --upgrade pip
      sudo pip install /vagrant --upgrade
SHELL
end